"""create decisions table

Revision ID: 2660e69f3882
Revises: 
Create Date: 2025-12-23 13:03:41.778024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2660e69f3882'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('decision_made_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_decision_key'), 'decisions', ['decision_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_decision_key'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
