"""add decision comparison table

Revision ID: 5d8b2aef6ee4
Revises: bbcab451d421
Create Date: 2025-12-23 17:15:00.455519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8b2aef6ee4'
down_revision: Union[str, Sequence[str], None] = 'bbcab451d421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_key', sa.String(), nullable=False),
    sa.Column('version_a', sa.Integer(), nullable=False),
    sa.Column('version_b', sa.Integer(), nullable=False),
    sa.Column('comparison_text', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_comparisons_decision_key'), 'decision_comparisons', ['decision_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_comparisons_decision_key'), table_name='decision_comparisons')
    op.drop_table('decision_comparisons')
    # ### end Alembic commands ###
