"""add decision explanations table

Revision ID: bbcab451d421
Revises: 2660e69f3882
Create Date: 2025-12-23 13:21:11.387996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcab451d421'
down_revision: Union[str, Sequence[str], None] = '2660e69f3882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('decision_key', sa.String(), nullable=False),
    sa.Column('decision_version', sa.String(), nullable=False),
    sa.Column('explanation_text', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_summary', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_explanations_decision_id'), 'decision_explanations', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_explanations_decision_key'), 'decision_explanations', ['decision_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_explanations_decision_key'), table_name='decision_explanations')
    op.drop_index(op.f('ix_decision_explanations_decision_id'), table_name='decision_explanations')
    op.drop_table('decision_explanations')
    # ### end Alembic commands ###
